import Footer from "@/componets/Footer";
import Navbar from "@/componets/Navbar";
import "@/styles/globals.css";
import { Montserrat } from "next/font/google";
import Head from "next/head";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-mont",
});

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Asrat Adane</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`${montserrat.variable} font-mont bg-light w-full h-auto`}
      >
        <Navbar />
        <Component {...pageProps} />
        <div className="h-1  bg-dark w-full"/>
         <Footer/>
      </main>
    </>
  );
}
